### ISSUE TITLE
Selecting Log items doesn't inspector select in Artifice_EditorWindow_Validator

### ISSUE THREAD

**Issue by Lgk2** [AbZorbaGames/artificetoolkit#59]
Currently you can select a Log Item in the Artifice_EditorWindow_Validator but it does not select the item in the inspector, in order to select the underlying object you need to double click the log item. I think this is a bit counter intuitive I think it should select the underlying object (the monobehaviour/scriptableobject/other thing) when you select the log item. Maybe you could change it so that items only get selected when double clicked or you could keep the current selection behaviour and select the item when single clicked and/or up down buttons are pressed.

**Comment by ZackPer** [comment]
I cant disagree with this. It will be updated soon.

**Comment by ZackPer** [comment]
Fixed in #62

**Comment by Lgk2** [comment]
Wouldn't it be cleaner if you add _logsListView.selectionChanged in BuildLogsUI and then you do the same thing as you do in this ClickEvent callback but in there, then you don't need a callback for every single item and it responds to other events that selects an item such as using up/down buttons on the keyboard?

To me it feels more natural if the selection is the thing that causes the item to be selected rather than the click, the click is just one way to select it.

**Comment by Lgk2** [comment]
Hey @ZackPer, quick follow-up in case you missed my last comment - thanks again!
